spring:
  mail:
    host: smtp.gmail.com       # Adres serwera SMTP
    port: 587                    # Port SMTP (zwykle 587 dla TLS)
    username: zarobkimarekszulak@gmail.com # Login do konta e-mail
    password: -------       # Hasło do konta e-mail
    properties:
      mail:
        smtp:
          auth: true             # Wymagane uwierzytelnianie
          starttls:
            enable: true         # Włączenie TLS dla bezpieczeństwa
  profiles:
    active: loadInitialData
  datasource:
    url: "jdbc:h2:mem:testdb"
    driver-class-name: "org.h2.Driver"
    username: "sa"
    password: "password"
  h2:
    console:
      enabled: true

mail:
  from: no-reply@fitnesstracker.com    # Domyślny adres nadawcy
